### ISSUE TITLE
Recompilation Issues with version 6.0.0.7

### ISSUE THREAD

**Issue by lchaganthi** [FrankGasparovic/Windows-Desktop-SSO-Node#5]
Hello,

I am trying to use this as part of migration from Kerberoes chain to Tree.I am facing issues with certain variabiliazation when trying to recompile with 6.0.0.7.Hopefully this module will work for 6.0 as i see it is coded for 6.5

below is the error i get.

[INFO] -------------------------------------------------------------
[ERROR] /C:/code/Windows-Desktop-SSO-Node-1.0.4/src/main/java/org/forgerock/openam/auth/nodes/WindowsDesktopSSONode.java:[169,83] cannot find symbol
  symbol:   variable request
  location: class org.forgerock.openam.auth.nodes.WindowsDesktopSSONode
[ERROR] /C:/code/Windows-Desktop-SSO-Node-1.0.4/src/main/java/org/forgerock/openam/auth/nodes/WindowsDesktopSSONode.java:[422,12] cannot find symbol
  symbol:   method setIsInitiator(boolean)
  location: variable wtc of type com.sun.identity.authentication.modules.windowsdesktopsso.WindowsDesktopSSOConfig
[INFO] 2 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.596 s
[INFO] Finished at: 2020-06-09T13:17:55-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project windowsdesktopsso-auth-node: Compilation failure: Compilation failure:
[ERROR] /C:/code/Windows-Desktop-SSO-Node-1.0.4/src/main/java/org/forgerock/openam/auth/nodes/WindowsDesktopSSONode.java:[169,83] cannot find symbol
[ERROR]   symbol:   variable request
[ERROR]   location: class org.forgerock.openam.auth.nodes.WindowsDesktopSSONode
[ERROR] /C:/code/Windows-Desktop-SSO-Node-1.0.4/src/main/java/org/forgerock/openam/auth/nodes/WindowsDesktopSSONode.java:[422,12] cannot find symbol
[ERROR]   symbol:   method setIsInitiator(boolean)
[ERROR]   location: variable wtc of type com.sun.identity.authentication.modules.windowsdesktopsso.WindowsDesktopSSOConfig

**Comment by FrankGasparovic** [comment]
Hi lchaganthi,

Unfortunately the Kerberos node only works on AM 6.5.2 and above due to a change in the Authentication Node Framework. For 6.0.0.7 you will need to use the WDSSO Module or migrate to a newer version of AM to take advantage of this node.

Thanks,

Frank
